### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by ghost** [HTML5-Games/html5-games.github.io#1]

**Comment by logan-r** [comment]
Sorry! This repo was created to let [html5-games.github.io](http://html5-games.github.io) be customized.

**Comment by AMPITUP** [comment]
I'm already part of the Vilify team, but can I join this project? I'm pretty advanced in HTML5/CSS3 positioning/styling/setup as well as some jQuery and a lot of JS. I didn't know where to apply, so I just posted here. sRy if this is the wrong spot.

**Comment by logan-r** [comment]
Sure, go ahead! You should have push/pull access to this repo.

**Comment by AMPITUP** [comment]
Ok, thx.
