### ISSUE TITLE
wanted to submit a game 

### ISSUE THREAD

**Issue by AALEKH** [HTML5-Games/html5-games.github.io#15]
Buddy, I want to a submit a game on this site please help me with it.....

**Comment by TheSentinel387** [comment]
@Aalekh-
if said game is the game mentioned in issue #16, we're going to close #16.
We (might) create a submissions file... maybe....

On 19 September 2013 11:21, Aalekh Nigam notifications@github.com wrote:

> Buddy, I want to a submit a game on this site please help me with it.....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HTML5-Games/html5-games.github.io/issues/15
> .

## 

++aLL Is DuSt++
